### ISSUE TITLE
✨ |svelte seployment| dockerize sveltekit frontend

### ISSUE THREAD

**Issue by jkrobicki** [dyvenia/timeflow#474]

**Comment by alivalizada** [comment]
Docker image needs to be build in order to add frontend to add into docker-compose file.

**Comment by alivalizada** [comment]
"npm run build" command is incorrectly creating two images (one of them "none")

**Comment by alivalizada** [comment]
deployment and exposing with caddy works. in Dockerfile, additional line has been added:

CMD ["npm", "run", "preview"]
